version: "3"

services:     
  back:
    image: venatorr/gridpoint_back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gridpoint_back:/gridpoint_back
    ports:
      - "8000:8000"
  front:
    image: venatorr/gridpoint_front
    ports: 
      - '8080:80'
  agent:
    image: venatorr/gridpoint_agent
    command: python background.py
    depends_on:
      - back